config/routes.rb
Rails.application.routes.draw do
  root to: 'diaries#index'
  devise_for :users
  resources :diaries, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  resources :comments, only: :create 
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary

  validates :comment_text, presence: true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
 
  validates :title, presence: true
  validates :text, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :hamster_name, presence: true
  validates :profile, presence: true
       
  has_many :diaries
  has_many :comments  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :hamster_name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to diary_path(@comment.diary)
    else
      @diary = @comment.diary
      @comments = @diary.comments
      render "diaries/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id, diary_id: params[:diary_id])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @diaries = Diary.includes(:user)
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @diary.comments
  end

  def edit
  end

  def update
    if @diary.update(diary_params)
      redirect_to diary_path(@diary)
    else
      render :edit
    end
  end

  def destroy
    if @diary.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :text, :image).merge(user_id:current_user.id)
  end

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @diary.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_diary.html.erb
<div class="card">
  <%= link_to image_tag(diary.image, class: :card__img ), diary_path(diary) %>
  <div class="card__body">
    <%= link_to diary.title, diary_path(diary), class: :card__title%>
    <p class="card__summary">
      <%= diary.text %>
    </p>
    <%= link_to "by #{diary.user.nickname}", user_path(diary.user), class: :card__user %>  
 </div>
</div>

app/views/diaries/_form.html.erb
<%= form_with model: @diary, local: true do |f|%>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text, "育成日記" %><br />
    <%= f.text_area :text, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "ハムスターの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">育成日記編集</h2>
      <%= render partial: "form", locals: { diary: @diary } %>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        Hello!,
        <%= link_to "#{current_user.nickname}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
  </div>
  <div class="contents">
   <div class="first-view">
    <%= image_tag "IMG_0013.JPG", class: 'top-image' %>
   </div>
   <div class="upper-content">
    <h1 class="heading-name">ハムスターと長く楽しく暮らそう</h1>
      <ul class="messages">
        <li class="message">
          ハムスターは子どもから大人まで幅広い世代に、非常に人気のある動物です。ハムスターの１日は人間にとって１ヶ月にもなります。ハムスターの寿命はゴールデンで３年ドワーフで２年ほど。ハムスターと過ごす１日１日を大切に楽しく過ごすためにこの育成日記を使って、できるだけ多くのハムスターと飼い主さんとのきずなを深めるために使っていただけると嬉しいです。それではかわいいハムスターとの暮らしを始めましょう！</div>
        </li>
      </ul>
   </div>
   <div class="middle-content">
    <h1 class="heading-name">ハムスターのミリョク</h1>
      <ul class="ham-charm-list">
       <li>
         <%= image_tag "IMG_1358.jpg", class: "ham-image" %>
         <h2 class="ham-charm-title">表情が豊かです。</h2>
           <p class="ham-charm">
            小さな体のハムスターですが、<br>
            表情が豊かで、目、鼻、口、耳で<br>
            いろいろなことを表現しています。
          </p>
        </li>
        <li>
          <%= image_tag "IMG_1012.jpg", class: "ham-image" %>
          <h2 class="ham-charm-title">どこにでも入ります。</h2>
          <p class="ham-charm">
            狭い場所が大好きで、どこにでも<br>
            入ってしまいます。時には驚く<br>
            ような場所から出てくることも。
          </p>
        </li>
        <li>
          <%= image_tag 'IMG_1211.jpg', class: 'ham-image' %>
          <h2 class="ham-charm-title">食いしん坊です。</h2>
           <p class="ham-charm">
            食にはとても貧欲です！<br>
            たくさん動くから、エネルギーが<br>
            たくさん必要なんです。
           </p>
        </li>
      </ul>
   </div>
   <div class="middle-content">
      <ul class="ham-charm-list">
        <li>
          <%= image_tag 'IMG_0542.jpg', class: 'ham-image' %>
          <h2 class="ham-charm-title">よく寝ます。</h2>
          <p class="ham-charm">
            とにかくよく寝ます。ゲージを掃除<br>
            する時などで、狭い部屋に移動しても<br>
            すぐ寝ます。寝る子は育つんです。
          </p>
        </li>
        <li>
          <%= image_tag "IMG_0394.jpg", class: "ham-image" %>
          <h2 class="ham-charm-title">飼い主さんになつきます。</h2>
          <p class="ham-charm">
            慣れてくれば、飼い主さんの<br>
            手や体に乗ってきます。安心して<br>
            しばらく動かなくなることも。
          </p>
        </li>
        <li>
          <%= image_tag "IMG_0598.jpg", class: "ham-image" %>
          <h2 class="ham-charm-title">後ろ姿もキュートです。</h2>
          <p class="ham-charm">
            かわいいのは顔だけではありません。<br>
            ぼてっとした丸い背中やお尻が<br>
            とてもキュートです。
          </p>
        </li>
      </ul>
    </div>
    <h1 class="heading-name">育成日記投稿一覧</h1>
    <div class="card__wrapper">
        <%= render partial: 'diary', collection: @diaries %>
    </div>
  </div>
</main>

app/views/diaries/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">育成日記投稿</h2>
      <%= render partial: "form", locals: {diary: @diary} %>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<main class="main">
  <div class="inner">
    <div class="diary__wrapper">
      <p class="diary__hedding">
        <%= @diary.title %>
      </p>
      <%= link_to "by #{@diary.user.nickname}", user_path(@diary.user), class: :diary__user %>
      <% if current_user == @diary.user %>
        <div class="diary__manage">
          <%= link_to "編集する", edit_diary_path, class: :diary__btn %>
          <%= link_to "削除する", diary_path(@diary), method: :delete,class: :diary__btn %>
        </div>
      <% end %>
      <div class="diary__image">
        <%= image_tag @diary.image %>
      </div>
      <div class="diary__body">
        <div class="diary__detail">
          <p class="diary__title"> 育成日記</p>
          <p class="detail__message">
            <%= @diary.text %>
          </p>
        </div>
      </div>
      <div class="diary__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@diary, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :comment_text, "コメント" %><br />
              <%= f.text_field :comment_text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% end %>
        <ul class="comments_lists">
         <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.comment_text %>
              <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
            </li>
           <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/home/index.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <title>with My HAMSTER</title>
  </head>
  <body>
    <header>
      <div class="heading">
        <h1 class="title">with My HAMSTER -ハムスターと暮らそう-</h1>
      </div>
      <div class="navbar">  
        <ul class="nav-lists">
          <li>ハムスターについて</li>
          <li>育成日記</li>
          <li>グッズ</li>
          <li>ログイン</li>
          <li>新規登録</li>
        </ul>
      </div>
    </header>

    <div class="contents">
      <div class="first-view">
        <%= image_tag 'IMG_0013.JPG', class: 'top-image' %>
      </div>
      <div class="upper-content">
        <h2 class="heading-name">ハムスターと長く楽しく暮らそう</h2>
        <ul class="messages">
          <li class="message">
            ハムスターは子どもから大人まで幅広い世代に、非常に人気のある動物です。ハムスターは知ってるけど、実際どうやって飼育すればいいのか？などインターネットで検索すれば、たくさんの情報がありますが、このアプリを通じて改めてハムスターについて知って欲しいことと、できるだけ多くのハムスターが、快適な環境で幸せに生活でき、飼い主さんとのきずなを深めるために使っていただけると嬉しいです。</div>
          </li>
        </ul>
      </div>
      <div class="middle-content">
        <h2 class="heading-name-two">ハムスターのミリョク</h2>
        <ul class="ham-charm-list">
          <li>
            <%= image_tag "IMG_1358.jpg", class: "ham-image" %>
            <h3 class="ham-charm">表情が豊かです。</h3>
            <p class="ham-charm">
            小さな体のハムスターですが、<br>
            表情が豊かで、目、鼻、口、耳で<br>
            いろいろなことを表現しています。
            </p>
          </li>
          <li>
            <%= image_tag "IMG_1012.jpg", class: "ham-image" %>
            <h3 class="ham-charm">どこにでも入ります。</h3>
            <p class="ham-charm">
            狭い場所が大好きで、どこにでも<br>
            入ってしまいます。時には驚く<br>
            ような場所から出てくることも。
            </p>
          </li>
          <li>
            <%= image_tag 'IMG_1211.jpg', class: 'ham-image' %>
            <h3 class="ham-charm">食いしん坊です。</h3>
            <p class="ham-charm">
            食にはとても貧欲です！<br>
            たくさん動くから、エネルギーが<br>
            たくさん必要なんです。
            </p>
          </li>
        </ul>
      </div>
      <div class="bottom-content">
      <ul class="ham-charm-list">
        <li>
            <%= image_tag 'IMG_0542.jpg', class: 'ham-image' %>
            <h3 class="ham-charm">よく寝ます。</h3>
            <p class="ham-charm">
            とにかくよく寝ます。ゲージを掃除<br>
            する時などで、狭い部屋に移動しても<br>
            すぐ寝ます。寝る子は育つんです。
            </p>
          </li>
          <li>
            <%= image_tag "IMG_0394.jpg", class: "ham-image" %>
            <h3 class="ham-charm">飼い主さんになつきます。</h3>
            <p class="ham-charm">
            慣れてくれば、飼い主さんの<br>
            手や体に乗ってきます。安心して<br>
            しばらく動かなくなることも。
            </p>
          </li>
          <li>
            <%= image_tag "IMG_0598.jpg", class: "ham-image" %>
            <h3 class="ham-charm">後ろ姿もキュートです。</h3>
            <p class="ham-charm">
            かわいいのは顔だけではありません。<br>
            ぼてっとした丸い背中やお尻が<br>
            とてもキュートです。
            </p>
         </li>
      </ul>
      </div>
    </div>

    <footer>
      <p>Copyright(C) with My HAMSTER ALL RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>with My HAMSTER</title>
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <h1><%= link_to "with My HAMSTER -ハムスター育成日記-", root_path %></h1>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "育成日記投稿", new_diary_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Atsushi Tanaka 【contact】 napa1215@icloud.com</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">ハムスターネーム</th>
            <td class="table__col2"><%= @user.hamster_name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの育成日記"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'diaries/diary', collection: @user.diaries %>
      </div>
    </div>
  </div>
</div>